# Generated by Django 3.2.5 on 2021-08-07 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='submit_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('resource_category', models.CharField(max_length=200)),
                ('resource_link', models.URLField(max_length=10000, unique=True)),
                ('resource_info', models.TextField()),
                ('submited_date', models.DateTimeField(auto_now_add=True)),
                ('resource_submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
