# Generated by Django 3.2.6 on 2021-08-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_submit_resource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('social_media_handle', models.URLField(max_length=2000)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
