# Generated by Django 3.2.5 on 2021-08-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_resource_resource_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_info',
            field=models.CharField(max_length=1000),
        ),
    ]
