# Generated by Django 3.2.5 on 2021-08-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_resource_resource_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_unlike',
            new_name='like_Unlike',
        ),
    ]
