# Generated by Django 3.2.5 on 2021-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_rename_like_unlike_like_like_unlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_info',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
