# Generated by Django 3.2.5 on 2021-08-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20210805_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resource.category'),
        ),
    ]
