# Generated by Django 3.2.5 on 2021-08-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_resource_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_info',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
