# Generated by Django 3.2.5 on 2021-08-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_category_category_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_info',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
