# Generated by Django 3.2.5 on 2021-08-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0010_like_unlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_unlike',
            old_name='post',
            new_name='resource',
        ),
    ]
