# Generated by Django 3.2.6 on 2021-08-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_auto_20210808_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_unlike',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resource.article'),
        ),
    ]
