# Generated by Django 3.2.6 on 2021-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_alter_like_unlike_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_info',
            field=models.TextField(blank=True),
        ),
    ]
