# Generated by Django 3.2.6 on 2021-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_alter_article_article_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_info',
            field=models.TextField(blank=True, default='No information provided about this article'),
        ),
    ]
